<a href="https://colab.research.google.com/github/BountyHunter1999/Learning-Pytorch/blob/main/Basics/Looking_Into_Tensors(basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### Operations

#### Creation

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

#### Accessing




In [3]:
a[1]

tensor(1.)

#### Changing Type

In [4]:
float(a[1])

1.0

#### Changing Values

In [5]:
a[2] = 2.0
a

tensor([1., 1., 2.])

* **Python Lists or tuples of numbers are collections of Python objects individually allocated in memory** *boxed*  whereas,
* **PyTorch tensors or NumPy are views over(typical) contiguous memory blocks containing unboxed C numeric types rather than Python objects.** *unboxed*

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [8]:
points  = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
points = torch.tensor([
                       [4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]
                       ])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([
                       [4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]
                       ])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0,1] # 0th row 2nd column

tensor(1.)

In [17]:
points[0] # get the 2D representation

tensor([4., 1.])

#### Indexing

In [21]:
points[1:] # all rows after the first; implicitly all columns

tensor([[5., 3.],
        [2., 1.]])

In [22]:
points[1:, :] # all rows after the first; explicitly all columns

tensor([[5., 3.],
        [2., 1.]])

In [23]:
points[1:, 0] # all rows after the first; first column

tensor([5., 2.])

In [24]:
points[None] # adds a dimnesion of size 1 just like unsqueeze

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [25]:
points.shape

torch.Size([3, 2])

In [26]:
points[None].shape

torch.Size([1, 3, 2])

### Named Tuples

In [29]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.07220])

In [30]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [35]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))